# -*- coding: utf-8 -*-
"""TFM_Simpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6kcOgfxxzlVUQTnNHDEN1FpXv5RY-w3
"""

pip install simpy

"""# Ejercicio 1"""

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = 1/4

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    i: simpy.Resource(env, capacity=1)
    for i in range(1, 6)
}

# Métricas
esperas = {i: [] for i in range(1, 6)}
tiempos_nodo = {i: [] for i in range(1, 6)}
ocupacion = {i: 0 for i in range(1, 6)}
visitas_nodo = {i: 0 for i in range(1, 6)}

tiempo_sistema = []

# Tránsito
def siguiente_nodo(actual):

    if actual == 1:
        return np.random.choice([2, 3,5], p=[0.5, 0.4,0.1])

    elif actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])

    elif actual == 3:
        return 4

    elif actual == 4:
        return 5

    elif actual == 5:
        return 6

    return 6

# Cliente
def cliente(env, nombre):

    llegada = env.now
    visitas = 0

    nodo = 1

    while nodo != 6:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            servicio = random.expovariate(MU)

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 6):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 6):

    rho = ocupacion[i] / tiempo_total

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 6):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))

"""# Ejercicio 2

"""

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = {
    1: 1 / 3,
    2: 1 / 4,
    3: 1 / 4,
    4: 1 / 5,
    5: 1 / 3
}

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    i: simpy.Resource(env, capacity=1)
    for i in range(1, 6)
}

# Métricas
esperas = {i: [] for i in range(1, 6)}
tiempos_nodo = {i: [] for i in range(1, 6)}
ocupacion = {i: 0 for i in range(1, 6)}
visitas_nodo = {i: 0 for i in range(1, 6)}

tiempo_sistema = []

# Tránsito
def siguiente_nodo(actual):

    if actual == 1:
        return np.random.choice([2, 3,5], p=[0.5, 0.4,0.1])

    elif actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])

    elif actual == 3:
        return 4

    elif actual == 4:
        return 5

    elif actual == 5:
        return 6

    return 6

# Cliente
def cliente(env, nombre):

    llegada = env.now
    visitas = 0

    nodo = 1

    while nodo != 6:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            servicio = random.expovariate(MU[nodo])

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 6):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 6):

    rho = ocupacion[i] / tiempo_total

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 6):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = 1/4

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    1: simpy.Resource(env, capacity=2),
    2: simpy.Resource(env, capacity=1),
    3: simpy.Resource(env, capacity=1),
    4: simpy.Resource(env, capacity=1),
    5: simpy.Resource(env, capacity=2)
}

# Métricas
esperas = {i: [] for i in range(1, 6)}
tiempos_nodo = {i: [] for i in range(1, 6)}
ocupacion = {i: 0 for i in range(1, 6)}
visitas_nodo = {i: 0 for i in range(1, 6)}

tiempo_sistema = []

# Tránsito
def siguiente_nodo(actual):

    if actual == 1:
        return np.random.choice([2, 3,5], p=[0.5, 0.4,0.1])

    elif actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])

    elif actual == 3:
        return 4

    elif actual == 4:
        return 5

    elif actual == 5:
        return 6

    return 6

# Cliente
def cliente(env, nombre):

    llegada = env.now
    visitas = 0

    nodo = 1

    while nodo != 6:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            servicio = random.expovariate(MU)

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 6):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 6):

    rho = ocupacion[i] / (tiempo_total * chatbots[i].capacity)

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 6):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))

"""# Ejercicio 3

"""

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = {
    1: 1 / 2,
    2: 1 / 4,
    3: 1 / 4,
    4: 1 / 3,
    5: 1 / 2
}

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    i: simpy.Resource(env, capacity=1)
    for i in range(1, 6)
}

# Métricas
esperas = {i: [] for i in range(1, 6)}
tiempos_nodo = {i: [] for i in range(1, 6)}
ocupacion = {i: 0 for i in range(1, 6)}
visitas_nodo = {i: 0 for i in range(1, 6)}

tiempo_sistema = []

# Tránsito
def siguiente_nodo(actual):
    if actual == 1:
        return np.random.choice([2, 3], p=[0.5, 0.5])
    if actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])
    if actual == 3:
        return np.random.choice([4, 6], p=[0.4, 0.6])
    if actual == 4:
        return np.random.choice([5, 6], p=[0.1, 0.9])
    if actual == 5:
        return np.random.choice([1, 6], p=[0.1, 0.9])
    return 6

# Cliente
def cliente(env, nombre):

    llegada = env.now
    visitas = 0

    nodo = 1

    while nodo != 6:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            servicio = random.expovariate(MU[nodo])

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 6):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 6):

    rho = ocupacion[i] / tiempo_total

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 6):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))

"""# Ejercicio 4

"""

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = {
    1: 1 / 2,
    2: 1 / 4,
    3: 1 / 4,
    4: 1 / 3,
    5: 1 / 2
}

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    i: simpy.Resource(env, capacity=1)
    for i in range(1, 6)
}

# Métricas
esperas = {i: [] for i in range(1, 6)}
tiempos_nodo = {i: [] for i in range(1, 6)}
ocupacion = {i: 0 for i in range(1, 6)}
visitas_nodo = {i: 0 for i in range(1, 6)}

tiempo_sistema = []


# Tránsito
def siguiente_nodo(actual):
    if actual == 1:
        return np.random.choice([2, 3], p=[0.7, 0.3])
    if actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])
    if actual == 3:
        return 4
    if actual == 4:
        return 5
    if actual == 5:
        return np.random.choice([1, 6], p=[0.1, 0.9])
    return 6


# Cliente
def cliente(env, nombre):
    llegada = env.now
    nodo = np.random.choice([1, 3, 4], p=[0.6, 0.1, 0.3])
    visitas = 0

    while nodo != 6:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            servicio = random.expovariate(MU[nodo])

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 6):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 6):

    rho = ocupacion[i] / tiempo_total

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 6):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))

"""# Ejercicio 5"""

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = {
    1: 1 / 2,
    2: 1 / 4,
    3: 1 / 4,
    4: 1 / 3,
    5: 1 / 2,
    6: 1 / 3
}

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    i: simpy.Resource(env, capacity=1)
    for i in range(1, 7)
}

# Métricas
esperas = {i: [] for i in range(1, 7)}
tiempos_nodo = {i: [] for i in range(1, 7)}
ocupacion = {i: 0 for i in range(1, 7)}
visitas_nodo = {i: 0 for i in range(1, 7)}

tiempo_sistema = []


# Tránsito
def siguiente_nodo(actual):
    if actual == 1:
        return np.random.choice([2, 3, 6], p=[0.5, 0.3, 0.2])
    if actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])
    if actual == 3:
        return 4
    if actual == 4:
        return np.random.choice([5, 6], p=[0.9, 0.1])
    if actual == 5:
        return np.random.choice([1, 7], p=[0.1, 0.9])
    if actual == 6:
        return np.random.choice([2, 3, 4, 5, 7], p=[0.2, 0.2, 0.2, 0.2, 0.2])
    return 7


# Cliente
def cliente(env, nombre):
    llegada = env.now
    nodo = np.random.choice([1, 3, 4], p=[0.6, 0.1, 0.3])
    visitas = 0

    while nodo != 7:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            servicio = random.expovariate(MU[nodo])

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 7):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 7):

    rho = ocupacion[i] / tiempo_total

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 7):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))

"""# Ejercicio 1 con Erlang"""

import simpy
import random
import numpy as np

# Parámetros
np.random.seed(1)
random.seed(1)

LAMBDA = 1 / 5

MU = 1/4

N_CLIENTES = 100000

# Crear entorno simpy
env = simpy.Environment()

chatbots = {
    i: simpy.Resource(env, capacity=1)
    for i in range(1, 6)
}

# Métricas
esperas = {i: [] for i in range(1, 6)}
tiempos_nodo = {i: [] for i in range(1, 6)}
ocupacion = {i: 0 for i in range(1, 6)}
visitas_nodo = {i: 0 for i in range(1, 6)}

tiempo_sistema = []

# Tránsito
def siguiente_nodo(actual):

    if actual == 1:
        return np.random.choice([2, 3,5], p=[0.5, 0.4,0.1])

    elif actual == 2:
        return np.random.choice([3, 4], p=[0.6, 0.4])

    elif actual == 3:
        return 4

    elif actual == 4:
        return 5

    elif actual == 5:
        return 6

    return 6

# Cliente
def cliente(env, nombre):

    llegada = env.now
    visitas = 0

    nodo = 1

    while nodo != 6:

        visitas += 1
        visitas_nodo[nodo] += 1

        recurso = chatbots[nodo]

        instante_cola = env.now

        with recurso.request() as req:

            yield req

            espera = env.now - instante_cola
            esperas[nodo].append(espera)

            # Erlang con k=5 y lambda=2
            servicio = random.gammavariate(5, 1/2)

            yield env.timeout(servicio)

            fin_servicio = env.now

            tiempos_nodo[nodo].append(fin_servicio - instante_cola)
            ocupacion[nodo] += servicio

        nodo = siguiente_nodo(nodo)

    tiempo_sistema.append(env.now - llegada)

# Llegadas
def llegadas(env):

    for i in range(N_CLIENTES):

        env.process(cliente(env, f"C{i}"))

        interarrival = random.expovariate(LAMBDA)
        yield env.timeout(interarrival)

# Ejecutar
env.process(llegadas(env))
env.run()

# Resultados
print("\nTiempo medio de espera")

for i in range(1, 6):
    print(
        f"Chatbot {i}: "
        f"{np.mean(esperas[i]):.3f}"
    )

print("\nUtilización")

tiempo_total = env.now

for i in range(1, 6):

    rho = ocupacion[i] / tiempo_total

    print(
        f"Chatbot {i}: {rho:.3f}"
    )

print("\nNúmero medio en el sistema")


for i in range(1, 6):
    N = (visitas_nodo[i] / tiempo_total)* np.mean(tiempos_nodo[i])

    print(f"Chatbot {i}: {N:.3f}")

print("\nTiempo medio en sistema")

print(np.mean(tiempo_sistema))